#!/bin/bash

# ----------------------------------------------------------------------
#
# Shortcut for query balance by ${key_name} or ${address}(43)
#
# ----------------------------------------------------------------------

param=$1
if [[ ${#param} == 43 ]]; then
    hashgardcli bank account ${param}
else
    hashgardcli bank account $(hashgardcli keys show -a ${param})
fi
